### ISSUE TITLE
Delete your SECRET_KEY from your code base

### ISSUE THREAD

**Issue by pydanny** [volunteer-planner/volunteer_planner#12]
You have a critical security flaw in your code. This line needs to go https://github.com/volunteer-planner/volunteer_planner/blob/master/volunteer_planner/settings/production.py#L33

You need to do one of the following instead:

1. Import the value from a configuration file
2. Get the value from an environment variable.

**Comment by Doca** [comment]
that's true thanks!

**Comment by pydanny** [comment]
For https://github.com/volunteer-planner/volunteer_planner/blob/master/volunteer_planner/settings/local.py#L36-L43 you might want to consider something like:

``` python
SECRET_KEY = os.environ.get('SECRET_KEY', 'DEV-ENVIRONMENT'
```

That way it's easier to get started with the project. You can do this with the other local dev settings too. :wink:
