### ISSUE TITLE
Apply at Google Impact Challenge

### ISSUE THREAD

**Issue by tordans** [volunteer-planner/volunteer_planner#124]
There is this new "Impact Challenge" by Google. Maybe this would be a way for this project to get some funding so someone can work with more time on this?

For more please check:
- www.g.co/EureIdee
- https://www.youtube.com/watch?v=-pLnrdlsMC4

Does it fit the basic criteria? I think it does / or can:

```
Wonach suchen wir?
Bedeutung für die Gemeinschaft: Das Projekt wirkt sich positiv auf die Lebenssituation einer lokalen oder größeren Gemeinschaft aus oder unterstützt Organisationen in ihrer alltäglichen Arbeit.
```
Yes it does.
```
Innovation: Das Projekt nutzt digitale Hilfsmittel oder einen kreativen Ansatz, um ein bisher ungelöstes Problem zu beheben.
```
Yes it does.
```
Realisierbarkeit: Das Projekt kann erfolgreich von der sich bewerbenden Organisation durchgeführt werden.
```
Yes … well once you find an Organisation that is willing to be the "Schirmherr" for this project.
```
Reichweite: Das Projekt hat das Potenzial, ein Vorbild für andere Gemeinschaften oder Organisationen zu sein oder einer großen Anzahl von Menschen zu helfen.
```
Yes it can.

More Rules are described in https://impactchallenge.withgoogle.com/static/v6.387398667811369610/deutschland/downloads/rules.pdf

Tobias

PS: Disclaimer, I work for betterplace.org who support the Impact Challenge by Google. But I and we don't have anything to gain by this message :-). I just wanted to let you know.

**Comment by christophmeissner** [comment]
Hey there! That's a great thing, I guess.

**Comment by Doca** [comment]
We heared from this challenge already and we will apply ;-) Thanks
