### ISSUE TITLE
Switch positions of longtitude and latitude in the location form

### ISSUE THREAD

**Issue by XComp** [volunteer-planner/volunteer_planner#18]
Usually, geopositions are defined by a pair of latitude and longitude where latitude comes first. The location form lists both fields the other way around. To overcome wrongly set geopositions, the order of these two fields should be changed.

**Comment by Doca** [comment]
Yes! It was just a stupid mistake ;-P We change this

**Comment by christophmeissner** [comment]
Removed non-bug part from bug report and created a feature request instead: #21
