### ISSUE TITLE
New Logo?

### ISSUE THREAD

**Issue by tordans** [volunteer-planner/volunteer_planner#185]
Hey Guys, I see the web design improved greatly since the last time I looked at the side. Great job!

I was wondering what you thing about those logo ideas.
I played around with the idea of a mixed handwriting and sans serif typo to mix some playful-emotional style with some serious-planning style.

If you thing the time is worth spending I will look into detailing one of those logo versions.
Please +1 one that you like and tell me if I should continue working on it.

I havent done this kind of work for ages, so it might take me a few weeks to get a nice vector version of those ideas ready.

## Version A
![volunteer planner logo version a 2015-10-10](https://cloud.githubusercontent.com/assets/111561/10411262/63420766-6f5f-11e5-97a6-ce580c9c6187.png)

## Version B
![volunteer planner logo version b 2015-10-10](https://cloud.githubusercontent.com/assets/111561/10411261/6341820a-6f5f-11e5-94b7-8a15967dab9e.png)

## Version C
![volunteer planner logo version c 2015-10-10]
(https://cloud.githubusercontent.com/assets/111561/10411263/63999cc4-6f5f-11e5-8998-ee886ca041cc.png)

Cheers, Tobias

**Comment by Doca** [comment]
cool! Thanks a lot. I like A pretty much! Nevertheless I have to ask the designer we already talked to if he would mind if you will do the logo lol . I appreciate it much.

**Comment by tordans** [comment]
@Doca it's no problem to stop here. It's all just for fun until now :).

**Comment by tordans** [comment]
I'll close this idea for now. Let me know if there is any interest.
