### ISSUE TITLE
DateFormat for JS-Datepicker

### ISSUE THREAD

**Issue by pitpalme** [volunteer-planner/volunteer_planner#206]
[apply_template.html](https://github.com/volunteer-planner/volunteer_planner/blob/develop/scheduletemplates/templates/admin/scheduletemplates/apply_template.html:24) needs reasonable value for 'apply_form.js_date_format', so "default" is 
actually only fallback.

**Comment by christophmeissner** [comment]
Fixed with 57b4a876c03183d6d41ca65438a975c090b08112
