### ISSUE TITLE
Select organization member by username

### ISSUE THREAD

**Issue by pitpalme** [volunteer-planner/volunteer_planner#210]
Currently one has to know or find account id.
Giving username (=account name) would be more comfortable.
Alternatively search capability to reduce list in popup window could solve the 
problem.

**Comment by christophmeissner** [comment]
Should be fixed with 85813903d65d7a25f5919ad08fd8fbe9e8ffd51d

**Comment by pitpalme** [comment]
LGTM. Merged.

Is there a way to not display account ID but username in input field?
