### ISSUE TITLE
Refactor data models

### ISSUE THREAD

**Issue by chhantyal** [volunteer-planner/volunteer_planner#61]
If you have enough time, please consider refactoring model design in scheduler app. I am creating this issue hoping to kick start it soon rather than making patches to fix bad design.

With increase in users and data, this is becoming too slow and annoying to work with. For example, simple views like http://localhost:8000/admin/registration/registrationprofile/2324/ make > 4000 SQL queries.

This is also cause of bugs.
 
Best place to start: We should remove `TimePeriods` model and use datetime in `Need`, thus completely removing current relation. This will require data migration too. And many changes in codebase, off course. 

Please put your thoughts here. Some tests would be great before making any such changes.

**Comment by pitpalme** [comment]
Totally agree!!!

Chances any shifts significantly share TimePeriods - which could be a possible reason for data normalization within DB - are low, from my POV.
A shift (can we please, when doing refactoring, rename "Need" to "Shift" or anything else more appropriate?) simply has two attributes: start and end (date)time.
If I'm going to move several shift e.g. from "4pm-7pm" to "5pm-8pm" I'll just do it and not alter the same amount of "TimePeriod" objects ...

**Comment by pitpalme** [comment]
Wrote SQL that would migrate table and data, alas I was unable to incorporate it into a working django-migration ... :/

Unluckily we would need more simple data model to be able to modify shifts and notify users ...

**Comment by christophmeissner** [comment]
Closing this for being vague (not clear about what to do in exactly). Mentioned example of `TimePeriods ` model is solved already by c6f4e90c3c555eb56515f1526c34ec8c4d5216ce.
